export default {
    data: [{
        id: 'notebook',
        keyword: '笔记本',
        name: '笔记本选购指南',
        desc: '我们会为您筛选出合适的产品',
        category: [{
            id: 'jiatingshiyong',
            name: '家庭使用',
            icon: 'fez-video',
            desc: '我想上网、看电影等娱乐活动，保存一些小文件、照片等'
        }, {
            id: 'gaoxiaobangong',
            name: '高效办公',
            icon: 'fez-business',
            desc: '我希望能快速处理复杂文件，并且有较大存储空间'
        }, {
            id: 'gaoqingyouxi',
            name: '高清游戏',
            icon: 'fez-game',
            desc: '笔记本电脑能满足我玩高阶游戏的需求'
        }, {
            id: 'qingbobianxie',
            name: '轻薄便携',
            icon: 'fez-blue-plane',
            desc: '我经常带着它出差或旅行，需要轻薄便携，续航时长'
        }, {
            id: 'shejishiyong',
            name: '设计使用',
            icon: 'fez-graphics',
            desc: '我需要做工程制图、照片渲染、视频制作等多相关工作'
        }]
    }, {
        id: 'computer',
        keyword: '台式机',
        name: '台式机选购指南',
        desc: '我们会为您筛选出合适的产品',
        category: [{
            id: 'richangxuqiu',
            name: '日常需求',
            icon: 'fez-video',
            desc: '刷微博，斗地主，在线聊天和购物'
        }, {
            id: 'shangyongbangong',
            name: '商用办公',
            icon: 'fez-business',
            desc: '需要处理较多的数据文件，运行希望更流畅；最好自带offic软件'
        }, {
            id: 'yingyinyule',
            name: '影音娱乐/工程制图',
            icon: 'fez-enginee',
            desc: '可以满足在线看高清大片，运行速度要有保证；工程制图需求，内存要大，最好有SSD'
        }, {
            id: 'gaming',
            name: 'Gaming',
            icon: 'fez-game',
            desc: '专业级游戏显卡加持，运行要快、散热要好，不坑队友'
        }]
    }, {
        id: 'crt',
        keyword: '显示器',
        name: '显示器选购指南',
        desc: '我们会为您筛选出合适的产品',
        category: [{
            id: 'yingyinyule',
            name: '影音娱乐',
            icon: 'fez-video',
            desc: '我要入门级显示器，上网，电影，玩儿小游戏'
        }, {
            id: 'youxidianjing',
            name: '游戏电竞',
            icon: 'fez-game',
            desc: '我是游戏玩家or游戏爱好者，我想要我的显示装备配得上我超神的水平'
        }, {
            id: 'shejizhitu',
            name: '设计制图',
            icon: 'fez-graphics',
            desc: '我是设计师or摄影师or影视相关工作人员，我需要一个能够准确显示色彩的显示器'
        }, {
            id: 'gaoxiaobangong',
            name: '高效办公',
            icon: 'fez-business2',
            desc: '我想让显示器满足不同的需求，能够显示更多我想显示的内容，让工作更高效'
        }, {
            id: 'aiyanjiankang',
            name: '爱眼健康',
            icon: 'fez-machine',
            desc: '通过技术减少长期使用显示器带来的眼部负担'
        }, {
            id: 'gupiaojinrong',
            name: '股票金融',
            icon: 'fez-business',
            desc: '我需要看到更长的K线，分析更多的数据，可以实现分屏在一块屏幕上进行数据的同时显示'
        }, {
            id: 'shangyong',
            name: '商用广告机',
            icon: 'fez-office',
            desc: '我想买个显示器用于商业用途'
        }]
    }, {
        id: 'projector',
        keyword: '投影仪',
        name: '投影仪选购指南',
        desc: '我们会为您筛选出合适的产品',
        category: [{
            id: 'shangwubangong',
            name: '商务办公',
            icon: 'fez-video',
            desc: '我想买台小型会议使用，实现开灯直投，不会受环境光太大影响'
        }, {
            id: 'jiatingzhuiju',
            name: '家庭追剧',
            icon: 'fez-enginee',
            desc: '我希望在家可以追剧，躺在床上看电影，能够享受大屏生活'
        }, {
            id: 'bianxiechuxing',
            name: '便携出行',
            icon: 'fez-plane',
            desc: '我经常外出，需要实现手机同屏、自带电池，偶尔追剧'
        }, {
            id: 'gongchengjiaoxue',
            name: '工程/教学',
            icon: 'fez-finance',
            desc: '我需要在大型会议室、礼堂使用，能够满足复杂环境，清晰度要高'
        }]
    }, {
        id: 'printer',
        keyword: '打印机',
        name: '打印机选购指南',
        desc: '我们会为您筛选出合适的产品',
        category: [{
            id: 'jiatingdayin',
            name: '家庭打印',
            icon: 'fez-video',
            desc: '家用打印机，打印成本低，安装简单，操作便捷。'
        }, {
            id: 'shangwubangong',
            name: '商务办公',
            icon: 'fez-business',
            desc: '我希望打印机能快捷高效，高负荷打印文档。'
        }, {
            id: 'zhaopiandayin',
            name: '照片打印',
            icon: 'fez-pohot',
            desc: '轻松打印高品质照片，记录生活点滴。'
        }, {
            id: 'xueshengdayin',
            name: '学生打印',
            icon: 'fez-graphics',
            desc: '学生打印  我的打印机链接方便，颜值高体积小巧。'
        }]
    }, {
        id: 'vr',
        keyword: 'VR',
        name: 'VR选购指南',
        desc: '我们会为您筛选出合适的产品',
        category: [{
            id: 'chenqinyouxi',
            name: '沉浸游戏',
            icon: 'fez-game',
            desc: '我想要一台高端VR头显，可以玩身临其境，沉浸感十足的VR游戏，画面清晰无畸变，定位精准，并且可以佩戴眼镜使用，尽情畅玩。'
        }, {
            id: 'zhenhanguanying',
            name: '震撼观影',
            icon: 'fez-enginee',
            desc: '我希望VR一体机的配置可支持高清播放，流畅无卡顿，提供IMAX 3D及全景观影的服务，并且有较大存储空间。只要带上移动VR一体机，便可以感触全景视角所带来的视觉与听觉全方位刺激。'
        }, {
            id: 'xiaobaichangxian',
            name: '小白尝鲜',
            icon: 'fez-print',
            desc: '我希望先体验一下VR产品，不必花太多钱，用自己的手机就可以去体验有沉浸感的VR游戏和震撼的3D视频。'
        }]
    }]
}
